// <auto-generated/> - StyleCop hack to not enforce commentation errors in this file.

using NKart.Core.Marketing.Offer;

namespace NKart.Core
{
    using NKart.Core.Marketing.Offer;

    /// <summary>
    /// Extension methods for <see cref="IOffer"/>.
    /// </summary>
    public static partial class Extensions
    {
    }
}
