// <auto-generated/> - StyleCop hack to not enforce commentation errors in this file.

using NKart.Core.Models;

namespace NKart.Core
{
    using NKart.Core.Models;

    /// <summary>
    /// Extension methods for <see cref="ICountry"/>.
    /// </summary>
    public static partial class Extensions
    {
    }
}